### ISSUE TITLE
Confusions about data input(X, Y, Labels)

### ISSUE THREAD

**Issue by wangxinzhi0** [berenslab/uneye#4]
Hello! I have some confusions about data input(X, Y, Labels).
I notice that the data you give is separate. For X data, it's a 1000*1000 matrix. While my data is a n_samples*3 matrix. Each column represents X, Y, Labels respectively. I don't understand what your data stands for and whether my data can be used directly, or how to transform the data format to apply to the program.
Thanks for your time. I hope you will take some time to answer my questions.

**Comment by jobellet** [comment]
Hello,
we chose to separate the X and Y position and Labels but if you have all variables in one matrix (your_matrix), it is no problem at all! Just assign:
X = your_matrix[:,0]
Y = your_matrix[:,1]
Labels = your_matrix[:,2]

Then you can pass these three variables to the function. The reason why in our example, X, Y and Labels have already 2 dimensions is because we have several trials, each of length 1000 bins. But if your data is just one continuous time series, it will automatically be cut into smaller pieces if it is too large for the network.
Let me know if you have further questions.
Best
Marie

**Comment by mebellet** [comment]
Hello,
we chose to separate the X and Y position and Labels but if you have all variables in one matrix (your_matrix), it is no problem at all! Just assign:
X = your_matrix[:,0]
Y = your_matrix[:,1]
Labels = your_matrix[:,2]

Then you can pass these three variables to the function. The reason why in our example, X, Y and Labels have already 2 dimensions is because we have several trials, each of length 1000 bins. But if your data is just one continuous time series, it will automatically be cut into smaller pieces if it is too large for the network.
Let me know if you have further questions.
Best
Marie

**Comment by wangxinzhi0** [comment]
Thank you for your detailed answer! 
I have adopted  your advice, but there was a small mistake. I don’t think it ’s a problem with the data, but I can't figure out what ’s wrong. Main codes are as follow:

data = np.loadtxt(“path")
X = data[:,0]
Y = data[:,1]
Labels = data[:,2]
model = uneye.DNN(max_iter=500, sampfreq=1000,
             lr=0.001, weights_name='weights',
            min_sacc_dist=1,min_sacc_dur=6,augmentation=True,
             ks=5,mp=5,inf_correction=1.5,val_samples=30)
model.train(X,Y,Labels)

**ValueError**: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 30 and the array at index 1 has size 4

[TH34_img_Europe_labelled_MN.txt](https://github.com/berenslab/uneye/files/4342758/TH34_img_Europe_labelled_MN.txt)

**Comment by mebellet** [comment]
Could you add 
print(X.shape) 
to see the length of your input.
Thanks
Marie

**Comment by wangxinzhi0** [comment]
(4988,)
Number of classes: 4
Using GPU: False

![image](https://user-images.githubusercontent.com/45959771/76851608-85eb8d00-6884-11ea-9243-4a03c41adedc.png)

**Comment by mebellet** [comment]
Is the sampling frequency of this 1000 Hz? If so, this would be less than 5 seconds of data which is too little for training. The training function uses a subset of the data for validation. This is by default 30 "samples" (it's the parameter val_samples). If your input is just one time series and not a matrix of several samples, the time series will be cut into samples of 1 second. Generally, this is not a problem, if the time series is long enough. But in your case, you would have 4 samples only. Then, you cannot have 30 samples for validation. Therefore the bug.
Do you have more data available?

**Comment by wangxinzhi0** [comment]
Hello, 
When I use  the complete data (1000x1000) in your paper, it works correctly. While intercepting part of data(1000x24, it is the same size as my dataset), it will have an error. The trace back are as follow.
It seems that there is something wrong with the pool layer. Does experiment trials have influence? I would appreciate it if you could give a solution. 

**X=np.loadtxt(path)
Y=np.loadtxt(path)
Labels=np.loadtxt(path)
X = X[:,:24]
Y = Y[:,:24]
Labels = Labels[:,:24]**

Number of classes: 2
Using GPU: False
Training. Please wait.
Traceback (most recent call last):

  File "<ipython-input-17-a9297b7fb4f7>", line 1, in <module>
    runfile('D:/anaconda_python_exercise/dataset/1uneye/my_trial.py', wdir='D:/anaconda_python_exercise/dataset/1uneye')

  File "D:\Anaconda3\envs\py3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\envs\py3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/anaconda_python_exercise/dataset/1uneye/my_trial.py", line 65, in <module>
    model.train(X,Y,Labels)

  File "D:\anaconda_python_exercise\dataset\1uneye\uneye\classifier.py", line 257, in train
    out = self.net(Vbatch,key)[0] # network output

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\anaconda_python_exercise\dataset\1uneye\uneye\functions.py", line 95, in forward
    out['p1'] = self.p1(out['c1'])

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\modules\pooling.py", line 76, in forward
    self.return_indices)

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\_jit_internal.py", line 138, in fn
    return if_false(*args, **kwargs)

  File "D:\Anaconda3\envs\py3\lib\site-packages\torch\nn\functional.py", line 457, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)

RuntimeError: Given input size: (20x1x1). Calculated output size: (20x1x0). Output size is too small
