### ISSUE TITLE
Hand labeling tool

### ISSUE THREAD

**Issue by rederoth** [berenslab/uneye#6]
This looks really nice, thanks for the great work!
But since human labels are required when using U'n'Eye, I was surprised that you're not sharing your labeling tool. I know that there are some GUIs out there (like https://github.com/richardandersson/EyeMovementDetectorEvaluation), but I think it would really help the usability if you could share yours.
Many thanks in advance!

**Comment by philippberens** [comment]
In fact, the tool is available:
https://github.com/timnaher/iLabel
